In [4]:
import numpy as np

In [6]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version() :
    t1 = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i] + y[i] for i in range(len(x))]
    return time.time() - t1

def numpy_version() :
    t1 = time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x + y
    return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()

t1 = pure_python_version()
t2 = numpy_version()

print(f''' waktu running pure python adalah {round(t1,4)} detik. waktu running versi numpy adalah {round(t2,4)} detik. numpy di contoh ini {(round((t1/t2),4))} kali lebih cepat!''')

 waktu running pure python adalah 0.2259 detik. waktu running versi numpy adalah 0.005 detik. numpy di contoh ini 45.3071 kali lebih cepat!


In [9]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [10]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]],

]

In [14]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [20]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((6,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [35]:
np.linspace(0,5,30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

In [41]:
np.random.rand(5)

array([0.492385  , 0.09033253, 0.20291103, 0.80011467, 0.86293775])

In [50]:
np.random.rand(3,6)

array([[0.36435989, 0.33836464, 0.93418081, 0.5529715 , 0.80829851,
        0.51177327],
       [0.93109943, 0.04027362, 0.74302023, 0.61339786, 0.81166288,
        0.0764743 ],
       [0.47195252, 0.50603287, 0.05481556, 0.98332246, 0.3580185 ,
        0.07827449]])

In [84]:
np.random.randint(3,6)

4

In [88]:
np.random.randint(1,50,12)

array([30, 27, 44, 34, 23, 24, 47,  6, 28, 27, 20, 39])

In [94]:
my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,6],[7,8,9]],
array_2d = np.array(my_list2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]],
]

array_3d = np.array(my_list3)


In [95]:
array_1d.shape

(3,)

In [96]:
array_2d.shape

(1, 3, 3)

In [97]:
array_3d.shape

(3, 3, 3)

In [135]:
array_3d.reshape(27)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [127]:
array_3d.reshape(27).shape

(27,)

In [138]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [139]:
array_3d.reshape(-1).shape

(27,)

In [146]:
ranarr = np.random.randint(1,50,14)

In [147]:
ranarr.max()

49

In [148]:
ranarr.argmax()

7

In [149]:
ranarr.min()

5

In [150]:
ranarr.argmin()

1

In [161]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
x[4]

4

In [164]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
x[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [166]:
x[-2]

8

In [167]:
x[0:15:4]

array([0, 4, 8])

In [169]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
x[0:2] = 100
x

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [171]:
x_slice =x[0:2]

In [172]:
x_slice

array([100, 100])

In [173]:
x

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [174]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [175]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [176]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [178]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False])

In [179]:
x_bool = arr%4==0
x_bool

array([False, False, False,  True, False, False, False,  True, False])

In [ ]:
push ke GitHub dan kirim ke email saya di aldo.purwadhika@gmail.com link GitHub dan file .ipynb nya
